services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        VITE_SOCKETIO_SERVER: ${VITE_SOCKETIO_SERVER}
        VITE_SOCKETIO_PATH: ${VITE_SOCKETIO_PATH}
        VITE_PEER_BACKEND_URL: ${VITE_PEER_BACKEND_URL}
        VITE_PEER_SERVER_PATH: ${VITE_PEER_SERVER_PATH}
        VITE_PEER_SERVER_PORT: ${VITE_PEER_SERVER_PORT}
        VITE_PEER_SERVER_IS_SECURE: ${VITE_PEER_SERVER_IS_SECURE}
    environment:
      VITE_SOCKETIO_SERVER: ${VITE_SOCKETIO_SERVER}
      VITE_SOCKETIO_PATH: ${VITE_SOCKETIO_PATH}
      VITE_PEER_BACKEND_URL: ${VITE_PEER_BACKEND_URL}
      VITE_PEER_SERVER_PATH: ${VITE_PEER_SERVER_PATH}
      VITE_PEER_SERVER_PORT: ${VITE_PEER_SERVER_PORT}
      VITE_PEER_SERVER_IS_SECURE: ${VITE_PEER_SERVER_IS_SECURE}
    ports:
      - "3000:80"
    env_file:
      - .env

  service-socket:
    build:
      context: .
      dockerfile: apps/service-socket/Dockerfile
    ports:
      - "3010:3010"
    environment:
      PORT: 3010
    env_file:
      - .env

  service-p2p:
    build:
      context: .
      dockerfile: apps/service-p2p/Dockerfile
    ports:
      - "3020:3020"
    environment:
      PORT: 3020
    env_file:
      - .env

  # service-sfu:
  #   build:
  #     context: .
  #     dockerfile: apps/service-sfu/Dockerfile
  #   ports:
  #     - "3030:80"
