services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_SOCKETIO_SERVER: http://localhost:3046
      VITE_SOCKETIO_PATH: /base/socket.io
      VITE_PEER_BACKEND_URL: localhost
      VITE_PEER_SERVER_PATH: /
      VITE_PEER_SERVER_PORT: 3020
      VITE_PEER_SERVER_IS_SECURE: false

  service-socket:
    build:
      context: .
      dockerfile: apps/service-socket/Dockerfile
    ports:
      - "3010:3010"
    environment:
      PORT: 3010

  service-p2p:
    build:
      context: .
      dockerfile: apps/service-p2p/Dockerfile
    ports:
      - "3020:3020"
    environment:
      PORT: 3020

  # service-sfu:
  #   build:
  #     context: .
  #     dockerfile: apps/service-sfu/Dockerfile
  #   ports:
  #     - "3030:80"
